//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoTierMVCReview.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WGProductStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WGProductStatus()
        {
            this.WGProducts = new HashSet<WGProduct>();
        }
    
        public int ProdStatusID { get; set; }
        public string ProdStatusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WGProduct> WGProducts { get; set; }
    }
}
