//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoTierMVCReview.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WGProduct
    {
        public int ProdID { get; set; }
        public string ProdName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int ProdStatusID { get; set; }
        public Nullable<int> VendorID { get; set; }
    
        public virtual WGCategory WGCategory { get; set; }
        public virtual WGProductStatus WGProductStatus { get; set; }
        public virtual WGVendor WGVendor { get; set; }
    }
}
