//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoTierMVCReview.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZMoviesEntities : DbContext
    {
        public ZMoviesEntities()
            : base("name=ZMoviesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WGCategory> WGCategories { get; set; }
        public virtual DbSet<WGProduct> WGProducts { get; set; }
        public virtual DbSet<WGProductStatus> WGProductStatuses { get; set; }
        public virtual DbSet<WGVendor> WGVendors { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    }
}
